credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$E9x/S2.4w./3z2Y5.6U8/.J2.P7f8G9H0I1j2K3l4M5n6o7p8q9r0' # التشفير الصحيح لكلمة pass123
    rhendricks:
      email: rhendricks@gmail.com
      name: Richard Hendricks
      password: '$2b$12$T1U2V3W4X5Y6Z7A8B9C0D.I.t.7aB7g5j6k4L3M.GNs7L9m8n0o1' # التشفير الصحيح لكلمة def456
cookie:
  expiry_days: 30
  key: "a_random_secret_key_123"
  name: signal_prime_cookie
