credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$3/P8I.t.7aB7g5j6k4L3M.GNs7L9m8n0o1p2q3r4s5t6u7v8w9x0y'
    rhendricks:
      email: rhendricks@gmail.com
      name: Richard Hendricks
      password: '$2b$12$A1B2c3d4e5f6g7h8i9j0k.t.7aB7g5j6k4L3M.GNs7L9m8n0o1p2'
cookie:
  expiry_days: 30
  key: "a_random_secret_key_123"
  name: signal_prime_cookie
preauthorized:
  emails:
  - mels@gmail.com
